### ISSUE TITLE
iOS12?

### ISSUE THREAD

**Issue by ghr1234** [jacksonjesse/covidsafe-scanner#3]
Nice app. Is there any chance there could be an implementation of ContentView that runs on iOS < 13, please?
My swift is almost non-existent and I do not know what the new iOS13+ features this module is using actually do.

Thank you.

**Comment by jacksonjesse** [comment]
Hi there, thanks for the interest!

I’m afraid it would be pretty much impossible to do this with my current implementation, as I’m using SwiftUI for the interface and this is not backwards compatible with iOS 12 and below. The aim was to knock something up as quickly as possible, and using SwiftUI allowed me to do this, as opposed to UIKit which I’m much less familiar with and requires more effort to implement a baby app like this.
